name: Run Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: ğŸ”¬ Run Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: ğŸ”¥ Install Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: ğŸ³ Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: âŒ› Install dependencies
      run: bun install
    
    - name: ğŸ§ª Run Vitest tests
      run: bun run test
